### ISSUE TITLE
这个要如何加菜单

### ISSUE THREAD

**Issue by lepig** [nadirvishun/abp#1]
可以直接在后台里面添加菜单吗？

**Comment by nadirvishun** [comment]
后台里可以加

**Comment by lepig** [comment]
我在我本地homestead里部署了一下，可以正常进入后台。
然后点击左边的菜单栏发现全部是404

我其他的yii2项目 是正常的。 还需要配置哪里吗？

**Comment by nadirvishun** [comment]
参照yii2推荐的配置试下？[https://github.com/yiisoft/yii2-app-advanced/blob/master/docs/guide-zh-CN/start-installation.md](https://github.com/yiisoft/yii2-app-advanced/blob/master/docs/guide-zh-CN/start-installation.md)
照着这个配置应该是没有问题的。
